baseURL = "https://www.claireparker.co.uk"
languageCode = "en-gb"
title = "Claire Parker-Jones Blog"
theme = "hugo-ted"
author = "Claire Parker-Jones"

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "Interesting"
    weight = 1
    url = "/interesting"

[params]
  GithubID = "claireparker"
  TwitterID = "claireparkerpen"
  CodepenID = "your_codepen"
  LinkedInID = "your_linkedin"
  InstagramID = "claire_codes"
  Name = "Claire Parker-Jones"
  GoogleAnalytics = "your_google_analytics_id"
