baseURL = "https://www.clairecodes.com"
languageCode = "en-gb"
title = "Claire Codes"
theme = "hugo-ted"
author = "Claire Parker-Jones"
googleAnalytics = "UA-67279079-1"

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "Interesting"
    weight = 1
    url = "/interesting"

[params]
  GithubID = "claireparker"
  TwitterID = "claireparkerpen"
  GithubRepoID = "hugo-blog"
  CodepenID = "your_codepen"
  LinkedInID = "your_linkedin"
  InstagramID = "claire_codes"
  Name = "Claire Parker-Jones"
