baseURL = "https://www.clairecodes.com"
languageCode = "en-gb"
title = "clairecodes"
theme = "hugo-ted"
author = "Claire Parker-Jones"
googleAnalytics = "UA-67279079-1"
enableRobotsTXT = true

[menu]
  [[menu.header]]
    name = "Blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "About"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "Dev Diary"
    weight = 1
    url = "/dev-diary"

[params]
  GitHubID = "claire-codes"
  TwitterID = "claireparkerpen"
  GitHubRepoID = "hugo-blog"
  CodePenID = "clairecodes"
  LinkedInID = "claireparkerjones"
  InstagramID = "claire_codes"
  Name = "Claire Parker-Jones"
  Description = "The personal website, blog and dev diary of clairecodes"
  EmailAddress = "claire@clairecodes.com"
  DevToId =  "clairecodes"
[permalinks]
  blog = "/blog/:year-:month-:day-:title/`"
  dev-diary = "/dev-diary/:year-:month-:day/"